[package]
name = "mine-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
console = "0.15.11"
dialoguer = "0.11.0"
dirs = "6.0.0"
indicatif = "0.17.11"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.20"
